<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>scala</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Scala</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.scala</string>
				</dict>
			</dict>
			<key>match</key>
			<string>/\*\*/</string>
			<key>name</key>
			<string>comment.block.empty.scala</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^\s*)?/\*\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.scsala</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/(\s*\n)?</string>
			<key>name</key>
			<string>comment.block.documentation.scala</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>@(param|return|throws|exception|author|version|see|since|serial|serialField|serialData|deprecated)\b</string>
					<key>name</key>
					<string>keyword.other.documentation.scaladoc.scala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\{@link\s+[^\}]*\}</string>
					<key>name</key>
					<string>keyword.other.documentation.scaladoc.link.scala</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\w*),?\s?</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.declaration.scala</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.scala</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*([private|protected|override|implicit]*\s)?def\s(\w*([_|?|=]*)?))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.declaration.scala</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*case class\s(\w*))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.declaration.scala</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*case object\s(\w*))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.declaration.scala</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.scala</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*([private|protected|override]*\s)?object\s(\w*))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.declaration.scala</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.scala</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*([private|protected|override]*\s)?\s*class\s(\w*))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.declaration.scala</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*type\s(\w*))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.declaration.scala</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\s*trait\s(\w*))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s(extends|with)\s(\w*)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(import|package)\b\s*(.*)$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s(new)\s(\w*)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(case|else|for|if|return|while|yield|synchronized)\b</string>
			<key>name</key>
			<string>keyword.control.scala</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#typesAsParameter</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#returnTypes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(var|val|lazy val)\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(catch|finally|throw|try)\b</string>
			<key>name</key>
			<string>keyword.exception.scala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(abstract|final|sealed|private|protected|implicit|override)\b</string>
			<key>name</key>
			<string>keyword.identifiers.scala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Nil)\b</string>
			<key>name</key>
			<string>entity.name.class</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(do|match|new|with|this|Nil)\b</string>
			<key>name</key>
			<string>keyword.other.scala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(false|null|true)\b</string>
			<key>name</key>
			<string>constant.language.scala</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([A-Z][a-zA-Z]*)\b</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.scala</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.scala</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.scala</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.scala</string>
				</dict>
			</array>
		</dict>
		<key>generic</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>end</key>
			<string>\]</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\w*),?\s?</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#generic</string>
				</dict>
			</array>
		</dict>
		<key>quailfiedClassName</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w*)</string>
		</dict>
		<key>returnTypes</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[^:]:\s*(\w+)</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.scala</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.scala</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.scala</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.scala</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.scala</string>
						</dict>
					</dict>
					<key>end</key>
					<string>'| </string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.scala</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.scala</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.scala</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.language.scala</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\w+)\s*:(\s*)?([\w|_|?|\.]*)</string>
		</dict>
		<key>typesAsParameter</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\(((\w+)\s?:\s?(\w+),?)\)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.scala</string>
	<key>uuid</key>
	<string>158C0929-299A-40C8-8D89-316BE0C446E8</string>
</dict>
</plist>
